name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  publish-npm:
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup PNPM
        uses: pnpm/action-setup@v6.0.5
        with:
          version: 10.33.2
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 24
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Publish
        run: pnpm dlx semantic-release --branches master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
